#:kivy 1.0
#:import kivy kivy
#:import win kivy.core.window
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import ListAdapter kivy.adapters.listadapter.ListAdapter

<GuidePage>:
    Image:
        size_hint: 1, 1
        source: 'E:\GitWorkSpace\Spider\KivyApp\Images\Image\Bubbles.jpg'
    Button:

        height: 24
        text_size: self.width, None
        color: (1, 1, 1, .8)
        text: 'Start'
<HelpPage>:
<LoginPage>:
<MainHome>: